### ISSUE TITLE
image

### ISSUE THREAD

**Issue by iceman1001** [mtongsang/pm3Bruter#1]
Since I couldn't find a email, I open an issue instead.

Interesting approach with the pm3bruter.  What is it that you use the image capture for? What do you take pictures of to make a comparison?

**Comment by mtongsang** [comment]
Hi,

The image capture is used to identify valid tags. A picture is taken using a webcam for every tested tag. The pictures are compared to identify any 'difference'. Most RFID reader use a red and/or green  LED to identify valid tags. That is what this feature is looking for. This 'techique' can generally be used for other lock mechanisms as well (Windows lockscreen, physical doors etc.).

**Comment by iceman1001** [comment]
Ok, I understood that you were comparing something, but I didn't understand what it was you were looking at.  So you take a webcam, point it towards a reader and if there is a led difference,  then thats your trigger to have found a working id.

I like your idea. I guess I'll make a separate software of out it, instead of hooking into the pm3 client.
