### ISSUE TITLE
Ineraction via pm button

### ISSUE THREAD

**Issue by osysltd** [mtongsang/pm3Bruter#2]
Dear author,

Great impressive idea and nice implementation, thank you!! Most like will be fun in a standalone mode. Is some interaction via pm button like proxbrute already available?

Regards.

**Comment by mtongsang** [comment]
Thank you! I don't think standalone pm3 is an option since most of the 'computing' is done on the client. You can use a Raspberry Pi to do this.

**Comment by osysltd** [comment]
Thanks for the reply!
